<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.2.1" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.2.1" />
    <PackageReference Include="Cortex.Mediator" Version="3.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OlimpiaIT.Logging.Entities" Version="1.1.0" />
    <PackageReference Include="OlimpiaIT.Logging.Serilog.Database" Version="1.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Olimpia.Application\Olimpia.Application.csproj" />
    <ProjectReference Include="..\Olimpia.Infrastructure\Olimpia.Infrastructure.csproj" />
  </ItemGroup>

</Project>
